---
name: Matrix CI

on:  # yamllint disable-line rule:truthy
  push:
  pull_request:

jobs:
  yamllint:
    name: yamllint
    runs-on: ubuntu-latest
    steps:
      - name: Check out
        uses: actions/checkout@v4
      - name: Run yamllint
        uses: frenck/action-yamllint@v1.5.0
  ansible-lint:
    name: ansible-lint
    runs-on: ubuntu-latest
    steps:
      - name: Check out
        uses: actions/checkout@v4
      - name: Run ansible-lint
        uses: ansible/ansible-lint@v24.10.0
        with:
          requirements_file: requirements.yml
